package entity;
// Generated May 29, 2017 2:19:32 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Questionbank generated by hbm2java
 */
@Entity
@Table(name="questionbank"
    ,catalog="lmsdb"
)
public class Questionbank  implements java.io.Serializable {


     private Integer questionId;
     private String question;
     private String option1;
     private String option2;
     private String option3;
     private String option4;
     private String answer;

    public Questionbank() {
    }

    public Questionbank(String question, String option1, String option2, String option3, String option4, String answer) {
       this.question = question;
       this.option1 = option1;
       this.option2 = option2;
       this.option3 = option3;
       this.option4 = option4;
       this.answer = answer;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="question_id", unique=true, nullable=false)
    public Integer getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    
    @Column(name="question", nullable=false, length=500)
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }

    
    @Column(name="option1", nullable=false, length=200)
    public String getOption1() {
        return this.option1;
    }
    
    public void setOption1(String option1) {
        this.option1 = option1;
    }

    
    @Column(name="option2", nullable=false, length=200)
    public String getOption2() {
        return this.option2;
    }
    
    public void setOption2(String option2) {
        this.option2 = option2;
    }

    
    @Column(name="option3", nullable=false, length=200)
    public String getOption3() {
        return this.option3;
    }
    
    public void setOption3(String option3) {
        this.option3 = option3;
    }

    
    @Column(name="option4", nullable=false, length=200)
    public String getOption4() {
        return this.option4;
    }
    
    public void setOption4(String option4) {
        this.option4 = option4;
    }

    
    @Column(name="answer", nullable=false, length=200)
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }




}


