package entity;
// Generated May 29, 2017 2:19:32 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name="student"
    ,catalog="lmsdb"
)
public class Student  implements java.io.Serializable {


     private Integer studentId;
     private String downloadMaterials;
     private String messageAlart;
     private String personalMessage;

    public Student() {
    }

    public Student(String downloadMaterials, String messageAlart, String personalMessage) {
       this.downloadMaterials = downloadMaterials;
       this.messageAlart = messageAlart;
       this.personalMessage = personalMessage;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="student_id", unique=true, nullable=false)
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    
    @Column(name="downloadMaterials", nullable=false, length=30)
    public String getDownloadMaterials() {
        return this.downloadMaterials;
    }
    
    public void setDownloadMaterials(String downloadMaterials) {
        this.downloadMaterials = downloadMaterials;
    }

    
    @Column(name="messageAlart", nullable=false, length=200)
    public String getMessageAlart() {
        return this.messageAlart;
    }
    
    public void setMessageAlart(String messageAlart) {
        this.messageAlart = messageAlart;
    }

    
    @Column(name="personalMessage", nullable=false, length=200)
    public String getPersonalMessage() {
        return this.personalMessage;
    }
    
    public void setPersonalMessage(String personalMessage) {
        this.personalMessage = personalMessage;
    }




}


