package entity;
// Generated May 29, 2017 2:19:32 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="lmsdb"
)
public class User  implements java.io.Serializable {


     private Integer userId;
     private String userName;
     private String password;
     private String enrolmentType;

    public User() {
    }

    public User(String userName, String password, String enrolmentType) {
       this.userName = userName;
       this.password = password;
       this.enrolmentType = enrolmentType;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="user_id", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="userName", nullable=false, length=20)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="password", nullable=false, length=20)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="enrolmentType", nullable=false, length=65535)
    public String getEnrolmentType() {
        return this.enrolmentType;
    }
    
    public void setEnrolmentType(String enrolmentType) {
        this.enrolmentType = enrolmentType;
    }




}


